### ISSUE TITLE
Importing a page template after renaming it

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/templates-patterns-collection#24] opened 2020-11-24 09:55 UTC
- [ ] https://prnt.sc/voh4bz - after renaming a page template, if you click on Import ( without refreshing the page ), the name is not updated in the popup. Plus, the page content is not imported, it's empty. 
- [ ] https://prnt.sc/voh5rm - not sure if that’s ok

Moved from here https://github.com/Codeinwp/neve/pull/2249

**Comment by HardeepAsrani** [comment] 2021-02-24 13:38
- Yes, the name stays the same, I think the request is cached and that's why but the contact is indeed imported.
- Second issue I can't reproduce and think was fixed in past.

Can @mghenciu test this to see if that happens on your side?

**Comment by mghenciu** [comment] 2021-02-25 11:54
@HardeepAsrani 
For the second issue, yes, I couldn't reproduce it. But I can confirm that it also happened to me long ago.
I think it was an interpretation error, as those symbols are unicode/decimal entity or something like that, for **Dash**.
![image](https://user-images.githubusercontent.com/52494172/109149988-ed86a980-7770-11eb-8166-61bba9a2863c.png)

**Comment by mghenciu** [comment] 2021-03-03 13:34
Same thing happened to me now, when I tried to add a page with the name: **Location & Schedule**.
This is how it looked in My Library (Thumbnail on the left side)
![image](https://user-images.githubusercontent.com/52494172/109813274-cbd86700-7c35-11eb-9972-7f2afd1ca8cd.png)

**Closed** 2021-04-29 08:05 UTC
Labels: template-cloud
