### ISSUE TITLE
The icon block doesn't keep the color settings if the colors are selected from the palette colors

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/templates-patterns-collection#42] opened 2021-01-08 10:48 UTC
### Description:
The icon block doesn't keep the color settings if the colors are selected from the palette colors

### How to reproduce:
1. Add an icon to a page
2. Set the colors to be palette colors
3. Save the template and import it

### Reference:
Editor: https://prnt.sc/wix32w
Front-end: https://prnt.sc/wix3l7

### Technical info
* WordPress version: 5.6
* Neve: 2.9.5
* Neve pro: 1.3.2
* TPC: 1.1.2

**Comment by selul** [comment] 2021-01-14 14:05
@irinelenache I don't understand your issue. Do you mean that on a 2nd site the colors are not the same as the first one?

In order to be the same, global colors need to be the same. On page import, we don't import customizer level settings ( i.e global colors ) and only page related options.

**Comment by irinelenache** [comment] 2021-01-14 15:13
@selul 
I used the same instance and added 2 blocks, an icon and a button, both with palette colors https://prnt.sc/wnhpy4 https://prnt.sc/wnhqby and when i imported the template from the dashboard https://prnt.sc/wnhtby this is how it looked https://prnt.sc/wnhu1z . I saw now that if i import the template from the page editor ( https://prnt.sc/wni1yb ) the colors work fine.

**Comment by selul** [comment] 2021-01-14 15:26
I still don't understand it.

**Comment by irinelenache** [comment] 2021-01-18 14:53
@selul I tried to explain the issue in a video
https://www.loom.com/share/be20b8742b2346c8bd1d6dc98db22d8d
Can you please explain me why the template is different when it's imported from the dashboard and when it's imported from the editor? Thanks

**Comment by selul** [comment] 2021-01-26 11:10
@HardeepAsrani can you have a look, might be related to otter blocks icon block?

**Comment by HardeepAsrani** [comment] 2021-01-26 20:17
@selul @irinelenache That's because of the themes. Themes add color using CSS classes so not all themes support it. Can't really do anything about it.

**Comment by selul** [comment] 2021-01-27 07:36
@HardeepAsrani from my understanding is the same theme with the same settings on the same instance. When you export it and import it back on the same site is not using the correct colors. 

Can you also confirm this @irinelenache ?

**Comment by HardeepAsrani** [comment] 2021-01-27 11:22
Yea, that will be great. Meanwhile, I'll also take a look with Neve Pro.

**Comment by irinelenache** [comment] 2021-01-27 12:04
@HardeepAsrani @selul yes, i used the same theme with the same settings and same jurassic ninja instance to export and import the template back

**Comment by HardeepAsrani** [comment] 2021-01-31 11:13
Hey @irinelenache - I tried it on Jurassic Ninja and it worked just fine. Can you try on an online instance too?

**Comment by irinelenache** [comment] 2021-02-02 13:20
@HardeepAsrani https://electrical-bear.jurassic.ninja
user: demo
pass: pjwPjEP2y3ef

In pages there are two pages with the same name, the first is the page that i created the template from and the second is the imported one. The template has two otter blocks and two wordpress blocks.

**Comment by HardeepAsrani** [comment] 2021-02-02 19:11
This one?

Every time I import, it works just fine. Can someone else try to do it? @Soare-Robert-Daniel Can you reproduce this issue on your end?

<img width="1049" alt="Screen Shot 2021-02-03 at 12 37 42 AM" src="https://user-images.githubusercontent.com/2649903/106649772-09ef5600-65b8-11eb-8773-f9f65239ee96.png">

**Comment by irinelenache** [comment] 2021-02-04 13:02
@HardeepAsrani have you tried importing the template from the wp dashboard?

**Comment by HardeepAsrani** [comment] 2021-02-05 20:48
It's happening because we use CSS variables like `var(\u002d\u002dnv-secondary-accent)` which gets worse during importing from Admin because we use `wp_kses_post` - can we afford to remove that validation? @abaicus

**Comment by HardeepAsrani** [comment] 2021-02-05 20:58
If you use two slashes `--` then Guten converts it to `\u002d\u002d` - pretty shitty if you ask me. I think WP does the sanitization when you use wp_insert_post: https://github.com/WordPress/WordPress/blob/17ee62881a78fbcdf23bd90b95c91c6e5107841a/wp-includes/post.php#L3774 - let me know if you think we can remove it. @abaicus

**Comment by abaicus** [comment] 2021-02-08 08:55
@HardeepAsrani this seems to be the same issue [here](https://github.com/Codeinwp/templates-patterns-collection/pull/44/files). The easiest way was to do a strreplace that carters specifically to it: 

`str_replace( 'var(\\u002d\\u002dnv', 'var(--nv', $data['post_content'] )`

**Comment by HardeepAsrani** [comment] 2021-02-08 17:17
@abaicus Then above one should've fixed it too, right?

**Comment by abaicus** [comment] 2021-02-08 17:32
@HardeepAsrani no. this only applies when importing full templates inside the dashboard. It doesn't work when importing inside the editor itself :zany_face:

**Comment by abaicus** [comment] 2021-02-08 17:33
@HardeepAsrani Sorry, yes. You are right. It should work fine in the described circumstances. :+1:

**Comment by HardeepAsrani** [comment] 2021-02-08 19:09
Thanks, I'll close this issue then. cc @irinelenache

**Closed by HardeepAsrani** 2021-02-08 19:09 UTC
Labels: bug

**Comment by abaicus** [comment] 2021-02-08 19:22
@irinelenache it should work fine with the built zip from this PR https://github.com/Codeinwp/templates-patterns-collection/pull/51

**Comment by HardeepAsrani** [comment] 2021-02-08 19:30
FYI, I tried it on my side and it worked with that branch.

**Comment by irinelenache** [comment] 2021-02-09 12:19
Tested it and now the issue is fixed 👍  🚀
