### ISSUE TITLE
Services and About us 2 page templates importing different content

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/templates-patterns-collection#40] opened 2020-12-28 12:47 UTC
### Description:

Some page templates import different content than the preview.
**Services** - Imported: https://user-images.githubusercontent.com/67897586/103214828-3dd0bf00-491a-11eb-9ee1-c41ecb14f293.png
**About us 2** - Imported: https://user-images.githubusercontent.com/67897586/103214945-8e481c80-491a-11eb-82b3-16d9edc4950e.png

### How to reproduce:

1. Import **Services** or **About us 2** templates
2. Check the imported page and the preview

### Technical info
* WordPress version: 5.6
* Theme version: 2.9.5
* TPC: 1.1.2

**Comment by selul** [comment] 2021-01-04 08:46
@mghenciu do you know if here is something wrong or the expected behaviour?

**Comment by mghenciu** [comment] 2021-01-04 13:16
@selul 
This is **not a expected** behaviour.

It looks to be caused by the Template option, under **Page Attributes**.
Basically, when you import a Generic Page (made only with Gb) from TC, the default page template is set to **Page Builder Full Width (Neve)** and it will look like this:
![image](https://user-images.githubusercontent.com/52494172/103537935-fdcf8600-4e9d-11eb-9987-2ed81fa69b66.png)

And, normally (when Template is set to Default), it should look like this:
![image](https://user-images.githubusercontent.com/52494172/103538019-222b6280-4e9e-11eb-9d3e-f3585fe86f4e.png)

On the other hand, the Starter Sites from TC use the **Page Builder Full Width (Neve)** option, so making all pages use Default, will break some of them.

Maybe we can configure the layout settings in Customizer:
- making sure that the Sidebar is enabled only on blog pages (and in other places, if needed)
- disable the Page title 
- make sure the pages (both generic & from Starter sites) look good using Default option.

or we can use the individual Page settings, per page, when importing a demo without resetting them on Import.

**Comment by selul** [comment] 2021-01-07 08:37
closing this in favor of #41

**Closed by selul** 2021-01-07 08:37 UTC
