### ISSUE TITLE
Generate screenshots automatically when Saving Pages in TPC

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/templates-patterns-collection#164] opened 2022-09-09 14:04 UTC
### Description:

As [mentioned here](https://github.com/Codeinwp/templates-patterns-collection/issues/100), @HardeepAsrani already implemented this feature. And right now I am not sure if this issue is present only on my account or on others also.
Basically **when I am trying to save a page in cloud, it asks me for the Screenshot**, and without it - a warning appears (attached video).
<img width="1724" alt="Screenshot 2022-09-09 at 17 01 23" src="https://user-images.githubusercontent.com/52494172/189367996-7eb26c4f-c390-498d-8885-026ab98407b3.png">

If it happens to other accounts (being the main features of the plugin)- it should be fixed; but also if it happens only on my account - as it's saves a lot of time not to create the Screenshots manually for each page.

https://user-images.githubusercontent.com/52494172/189367303-5166dd52-cfd3-4f26-841d-04e44c4d9129.mov

**Comment by mghenciu** [comment] 2022-10-05 12:09
Tested with a **Agency License**, and it looks like the Screenshots are not generated:

https://user-images.githubusercontent.com/52494172/194056864-e5b69e89-ad5f-404a-866a-e7505fa25dbc.mov

**Comment by HardeepAsrani** [comment] 2022-10-07 19:01
I did some investigating and the issue seems to be somewhere here: https://github.com/Codeinwp/templates-cloud/blob/main/inc/class-assets-management.php#L381-L382 - the screenshot is generated properly when the method is run directly.

**Comment by preda-bogdan** [comment] 2022-11-22 11:10
@HardeepAsrani The action was missing a hook.
I think this: https://github.com/Codeinwp/templates-cloud/issues/46 will also solve this issue.

**Comment by mghenciu** [comment] 2022-12-23 12:41
As discussed with Bogdan, this should be done and can go into QA.
And I'll create another issue regarding the same thing, but for our admin side of publishing Pages.

cc. @irinelenache

**Comment by preda-bogdan** [comment] 2022-12-23 12:43
@mghenciu Thank you!
Since it is not related to the reported bug, we can just test to see that the reported bug is fixed and preview is saved for user templates.
We can open a new issue to improve the workflow for the design team when publishing pages.

**Comment by preda-bogdan** [comment] 2023-01-11 12:51
I checked this on a TasteWP instance and the screenshot is being saved. If the site is publicly available and the post is published it should save the screenshot.

@irinelenache can you double check this and confirm that is working for you also so we can close this? 

The changes to the Schedule should have solved this.

**Comment by irinelenache** [comment] 2023-01-11 13:44
@preda-bogdan I did a double check and the screenshot is saved for me in TasteWP 👍 

I also tested on InstaWP and it didn't work, but i found a weird pattern:

Saved a page and the screenshot wasn't generated. Tried to save a second page and now the screenshot for the first one was visible https://vertis.d.pr/i/zg9mE8 . Tried to save a third page and the screenshot for the second one was generated https://vertis.d.pr/i/UwtkxA . Maybe there's a logic problem that causes this

**Comment by preda-bogdan** [comment] 2023-01-11 13:48
@irinelenache thank you for looking into this, it might be that the screenshot is not yet available as it is ran on a scheduled job. So maybe instead of saving a new page, just try refreshing the Library using the refresh button. If it is available after refresh (some short time) than it is not an issue. If it is only available after a new page is saved I will check what else might be happening. So let me know, thank you!

**Comment by irinelenache** [comment] 2023-01-11 14:52
@preda-bogdan After using the sync button it worked as expected, thanks for the explanation 🚀

**Comment by preda-bogdan** [comment] 2023-01-11 15:05
@irinelenache Thank you for checking this again, will make this as closed as the issue is now resolved.

**Closed by preda-bogdan** 2023-01-11 15:05 UTC
Labels: bug
